import test from 'node:test';
import assert from 'node:assert/strict';
import { Container } from '../src/core/container.js';
import { EventBus } from '../src/core/event-bus.js';
import { PulCore } from '../src/core/pulcore.js';
import { AccessDeniedError } from '../src/core/acl.js';
import { accessControlPlugin } from '../src/plugins/access-control.js';
import { portalManagerPlugin } from '../src/plugins/portal-manager.js';
import { workflowPlugin } from '../src/plugins/workflow.js';
import { auditLogPlugin } from '../src/plugins/audit-log.js';
import { iotSuitePlugins } from '../src/plugins/iot-suite.js';
import { createParityPlugins, parityCatalog, parityCategoryCounts } from '../src/plugins/parity-catalog.js';

async function createFoundation() { const core = new PulCore(); const plugins = [...createParityPlugins({ 'access-control': accessControlPlugin, 'portal-manager': portalManagerPlugin, workflow: workflowPlugin, 'audit-log': auditLogPlugin }), ...iotSuitePlugins]; for (const plugin of plugins) core.plugins.install(plugin); for (const plugin of plugins) if (!plugin.requiresConfiguration) await core.plugins.enable(plugin.name); return core; }
test('container creates singleton services lazily', () => { const container = new Container(); let calls = 0; container.register('service', () => ({ call: ++calls })); assert.equal(container.resolve('service'), container.resolve('service')); assert.equal(calls, 1); });
test('event bus respects listener priority', async () => { const events = new EventBus(); const order = []; events.on('test', () => order.push('low')); events.on('test', () => order.push('high'), { priority: 10 }); await events.emit('test'); assert.deepEqual(order, ['high', 'low']); });
test('133 parity plugins are unique and match the declared category matrix', () => { assert.equal(parityCatalog.length, 133); assert.equal(new Set(parityCatalog.map((item) => item.name)).size, 133); assert.deepEqual(parityCategoryCounts, { 'data-source':13, 'collection-field':12, 'ui-block':11, action:9, workflow:20, security:13, integration:10, notification:3, queue:5, system:10, organization:4, personalization:11, other:12 }); });
test('every parity plugin has lifecycle metadata and a project contribution', async () => { const core = new PulCore(); const plugins = createParityPlugins(); for (const plugin of plugins) core.plugins.install(plugin); for (const plugin of plugins) if (!plugin.requiresConfiguration) await core.plugins.enable(plugin.name); const list = core.plugins.list(); assert.equal(list.length, 133); for (const plugin of list) { assert.ok(plugin.title); assert.ok(plugin.description); assert.ok(plugin.capabilities.length); assert.ok(Object.keys(plugin.contributes).length); assert.equal(plugin.license, 'Apache-2.0'); assert.equal(plugin.requiresConfiguration ? plugin.status === 'installed' && !plugin.configured : plugin.status === 'enabled' && plugin.configured, true); } });
test('external adapters cannot be enabled before valid configuration', async () => { const core = new PulCore(); const plugin = createParityPlugins().find((item) => item.name === 'data-source-mysql'); core.plugins.install(plugin); await assert.rejects(core.plugins.enable(plugin.name), /requires configuration: host/); assert.equal((await core.plugins.health(plugin.name)).status, 'needs_configuration'); assert.throws(() => core.plugins.configure(plugin.name, { host: 'db', database: 'app', username: 'user', password: 1 }), /password must be string/); core.plugins.configure(plugin.name, { host: 'db', database: 'app', username: 'user', password: 'secret' }); await core.plugins.enable(plugin.name); assert.equal(core.plugins.get(plugin.name).status, 'enabled'); });
test('full plugin matrix exposes 133 parity plugins plus seven PulCore extensions', async () => { const core = await createFoundation(); const list = core.plugins.list(); assert.equal(list.length, 140); assert.equal(new Set(list.map((item) => item.name)).size, 140); assert.equal(list.filter((item) => item.upstreamTier === 'parity').length, 133); assert.equal(list.every((item) => item.capabilities.length > 0), true); assert.equal(list.find((item) => item.name === 'device-protocol-gateway').capabilities.includes('iot.modbus.tcp'), true); assert.equal(list.find((item) => item.name === 'construction-equipment-app').capabilities.includes('equipment.maintenance'), true); });
test('plugin contract reports honest readiness rather than enabling unconfigured adapters', async () => { const core = await createFoundation(); const list = core.plugins.list(); for (const plugin of list) { assert.match(plugin.name, /^[a-z][a-z0-9-]*$/); assert.ok(plugin.title); assert.ok(plugin.description); assert.ok(plugin.version); assert.ok(plugin.capabilities.length); if (plugin.requiresConfiguration) { assert.equal(plugin.status, 'installed'); assert.equal(plugin.configured, false); } else assert.equal(plugin.status, 'enabled'); } });
test('plugin failures are isolated and observable', async () => { const core = new PulCore(); core.plugins.install({ name: 'broken', enable() { throw new Error('boom'); } }); await assert.rejects(core.plugins.enable('broken'), /boom/); assert.equal(core.plugins.list()[0].status, 'failed'); });
test('portal manager supports real CRUD through metadata', async () => { const core = await createFoundation(); const created = await core.execute({ role: 'admin', model: 'portal', action: 'create', input: { name: '客户门户', key: 'crm', mode: 'no-code', description: '客户业务入口', enabled: true } }); assert.equal(created.key, 'crm'); const list = await core.execute({ role: 'admin', model: 'portal', action: 'list' }); assert.equal(list.meta.total, 2); const updated = await core.execute({ role: 'admin', model: 'portal', action: 'update', id: created.id, input: { enabled: false } }); assert.equal(updated.enabled, false); });
test('ACL blocks anonymous foundation access', async () => { const core = await createFoundation(); await assert.rejects(core.execute({ role: 'anonymous', model: 'portal', action: 'list' }), AccessDeniedError); });
test('construction equipment example runs on metadata CRUD', async () => { const core = await createFoundation(); const project = await core.execute({ role: 'admin', model: 'construction_project', action: 'create', input: { name: '滨海中心项目', companyId: 'company_demo', code: 'XM-001', status: 'active', location: { city: '深圳' } } }); const equipment = await core.execute({ role: 'admin', model: 'equipment', action: 'create', input: { name: '3号塔式起重机', projectId: project.id, equipNo: 'EQ-003', category: '塔式起重机', model: 'TC6015', source: 'owned', status: 'working', isSpecial: true } }); assert.equal(equipment.projectId, project.id); const list = await core.execute({ role: 'admin', model: 'equipment', action: 'list', query: { projectId: project.id } }); assert.equal(list.meta.total, 1); assert.equal(list.data[0].equipNo, 'EQ-003'); });
